### PR TITLE
Windows FileSystemWatcher

### PR DESCRIPTION
**Pull request by SamPruden**
This is an experimental custom implementation of `FileSystemWatcher` using Windows APIs. This is similar to what would normally be used in .Net.

Apologies for another PR without pre-discussion! Again this is something I've done for my own personal use in my fork, and I'm making it available here if you want it, but please don't feel pressure to take it.

Unity/Mono has a bad implementation on Windows. I'm pretty sure it's just polling for changes, and as a result can be **slow**. Sometimes I see FSR take multiple seconds before the change event is triggered! This custom one is effectively instant.

It comes with a big caveat: I don't have high confidence in its correctness, yet. It's doing messy threading stuff, as well as dealing with Windows APIs. It has zero automated testing, other than that I'm using it in my local FSR and it hasn't broken yet. I've [posted it on the codereview stackexchange for a second pair of eyes](https://codereview.stackexchange.com/questions/285736). Please don't merge this without thorough review!

I also think the code style doesn't match FSR's right now. I can fix that if you want it. \*cough\* #89 \*cough\*

I reserve the right to release a version of this class as a separate library or similar in the future, as it has general applicability outside of FSR.

### CODE REVIEW

**Comment by handzlikchris** [comment]
> Apologies for another PR without pre-discussion
Haha - if only more people made such blunders! :)

This is a fairly self contained piece of code, not much to discuss - if it works, it works.

I lack the skills to properly review windows interop. Since you'd like to reuse/release I'd suggest slightly different approach.

We could:
- move the file to separate folder in Plugins 
   - then you can also add your MIT license on top of the file and it'll be clear it's reusable piece
   - with that approach coding style also doesn't need to be consistent with rest of codebase, it's a separate piece
- add asmdef that'll compile only with `FastScriptReload_UseNativeWinFileWatchers` preprocessor directive (or similar)
    - the asset also works on Mac / Linux, this should help if any compile time issues would arise on those platforms when trying to use Win interop
- add feature flag in Preferences (under File Watcher tab) that'll add that compilation flag (there's another setting that does similar thing already, although it's in LiveScriptReload) - [default initialization to false so users can opt-in initially]

eg:
```
        public static readonly ToggleProjectEditorPreferenceDefinition IsAssetIncludedInBuild = new ToggleProjectEditorPreferenceDefinition(
            "Enable Hot-Reload for build", "IsAssetIncludedInBuild", true,
            (newVal, oldVal) => BuildDefineSymbolManager.SetBuildDefineSymbolState(BuildSymbol_LiveScriptReload_IncludeInBuild, (bool)newVal),
            val => BuildDefineSymbolManager.SetBuildDefineSymbolState(BuildSymbol_LiveScriptReload_IncludeInBuild, (bool)val)
        );  
```

There's also on-launch check to make sure flag in correctly set, eg:
```
        static LiveScriptReloadWelcomeScreenInitializer()
        {
          //omitted for brevity
            BuildDefineSymbolManager.SetBuildDefineSymbolState(LiveScriptReloadPreference.BuildSymbol_LiveScriptReload_IncludeInBuild,
                (bool)LiveScriptReloadPreference.IsAssetIncludedInBuild.GetEditorPersistedValueOrDefault()
            );
        }
```

- add a note in FileWatcher tab to let people know about Unity FIle Watcher limitation and option to turn this approach on

With that people can generally opt in to use is and will help with testing (if this is farily robust we can then later default that feature flag to 'true' on windows).

Those changes should be quite quick if you know how UI/prefs are laid out - happy to add those later myself - there's a solid number of people that have FileWatcher related issues.

PS: I'm still away and will come back mid July, hopefully can get it merged once I'm back

Thanks again!

**Comment by handzlikchris** [comment]
I'll also do some testing on my end, just wondering have you tried adding multiple file-watchers for different issues?

With that approach that may not be needed but it'd be good to make sure that existing features around that are still working.

**Comment by handzlikchris** [comment]
Potentially related to reveiw after merge #11 #14 #12

**Comment by SamPruden** [comment]
> I lack the skills to properly review windows interop.

That's the issue; so do I. I think this looks right based on the docs, and it's working for me, but I don't have much experience dealing with interop and I'm a little concerned that there could be some black magic interop knowledge that I'm missing out on. Maybe somebody on the FSR discord has the experience; perhaps I'll ask there.

I do have the advantage of having also read Microsoft's version, which was pretty useful for things like looking at their error flow. However they're using the async version of `ReadDirectoryChangesW` whereas mine uses the sync version, because I hit some currently unexplained issues with it on Mono. If the async way had worked I could have just copied over the MS implementation with a few tweaks, and this would be less of an issue!

> Since you'd like to reuse/release

I don't have clear plans for that right now, but I should probably dump it on github. [We know at least one person](https://forum.unity.com/threads/filesystemwatcher-runs-too-slow-on-unity-editor.1308591/) who could probably use it. I'm just waiting until I feel a little more confident in it.

> move the file to separate folder in Plugins

That works. I can do that, but if it ever comes more convenient to absorb it into the rest of the code and to make FSR specific changes, I have absolutely no objection from a licensing perspective. This was written for FSR, I can just imagine other uses. For now, I've managed to not take any dependencies on Unity for reusabiltiy.

Assuming you want it in plugins as code rather than a binary, there are probably some issues with me using newer language features that aren't supported on older Unity versions. Actually, that might be true of all of my PRs, because I completely just didn't think of that! I'll go through and do a scan for problems there.

> add asmdef that'll compile only with FastScriptReload_UseNativeWinFileWatchers preprocessor directive

I was just going to be lazy and ifdef the whole file to avoid compiler issues, but I like your plan of making it 100% toggleable with a feature flag like this.

> I'll also do some testing on my end, just wondering have you tried adding multiple file-watchers for different issues?

To clarify, are you asking whether I've tested running multiple of these simultaneously? I have briefly, and it all seemed to work fine. There shouldn't be any issues in the code itself, because I don't touch statics or anyhing. In terms of the interop, there are no warnings in the documentation about using multiple simultaneously... Microsoft's `FileSystemWatcher` uses the same API and it works fine there, but they use the async version and I use the sync version, so that doesn't prove anything. This is the type of issue where I'd love an expert to chime in.

**Comment by SamPruden** [comment]
> To clarify, are you asking whether I've tested running multiple of these simultaneously? I have briefly, and it all seemed to work fine. There shouldn't be any issues in the code itself, because I don't touch statics or anyhing.

Actually... I should check whether `CancelIoEx` hits all instances of the directory opened by the process, or whether it's specific to the handle instance. Hopefully the latter, but I shouldn't assume.

**Comment by SamPruden** [comment]
I also want to review which threads I'm putting events on.

 - I'm currently doing a thing where I put errors on a separate thread from other events, which I think is probably bad.

 - They're all currently on worker threads. and I'm thinking maybe I should bump them up to having an exclusive thread, or bumping their priority up some other way. Currently, if no threads are available in the pool, events will be delayed.

**Comment by SamPruden** [comment]
There are a couple of things preventing this from compiling on 2019.3.

 - `FileSystemName.MatchesSimpleExpression` is missing. I'm using that to do name/filter matching. I'll probably need a custom implementation of this, but I can look at how that function is implemented.
 - `ReadOnlySpan<T>` is missing. This one is sad, as beautiful code will have to become a pointer mess, but it's easy enough to work around.

**Comment by SamPruden** [comment]
> Potentially related to reveiw after merge #11 #14 #12

Also #20

**Comment by leohilbert** [comment]
I've been using this custom watcher in my setup recently and it works great! It is really fast and also solves some other issues that prevents my files from being reloaded properly. However when using it sometimes Unity gets stuck in an endless loop during "Reload Domain" sometimes. This happens multiple times a day and is really annoying since I have to kill Unity using the Taskmanager and reboot it. I checked the running threads and it looked like it was the Filewatcher. 

I attached my thread stack and a screenshot of the responsible line `WindowsFileSystemWatcher:167`. Could this be related to your observations @SamPruden ?

Screenshot 2023-10-18 103335

```@21532

 @33496

 @2052

 @23904

 @17720
	[Native Transition]
	WindowsFileSystemWatcher.Monitor()
	WindowsFileSystemWatcher.<set_EnableRaisingEvents>b__41_0()
	Task.InnerInvoke()
	Task.Execute()
	Task.ExecutionContextCallback()
	ExecutionContext.RunInternal() [2]
	ExecutionContext.Run() [2]
	Task.ExecuteWithThreadLocal()
	Task.ExecuteEntry()
	ThreadPoolTaskScheduler.<>c.<.cctor>b__10_0()
	ThreadHelper.ThreadStart_Context()
	ExecutionContext.RunInternal() [1]
	ExecutionContext.Run() [1]
	ExecutionContext.Run()
	ThreadHelper.ThreadStart()

 @14624

 @5336

Burst-CompilerThread-1 @30644
	[Native Transition]
	WaitHandle.WaitMultiple()
	WaitHandle.WaitAny()
	WaitHandle.WaitAny()
	BlockingCollection<CompilerServerJob>.TryTakeFromAnyCoreSlow()
	BlockingCollection<CompilerServerJob>.TryTakeFromAnyCore()
	BlockingCollection<CompilerServerJob>.TakeFromAny()
	CompilationQueue.Take()
	CompilerThread.CompilerThreadLoop()
	ThreadHelper.ThreadStart_Context()
	ExecutionContext.RunInternal()
	ExecutionContext.Run()
	ExecutionContext.Run()
	ThreadHelper.ThreadStart()

Burst-CompilerThread-10 @32692
	[Native Transition]
	WaitHandle.WaitMultiple()
	WaitHandle.WaitAny()
	WaitHandle.WaitAny()
	BlockingCollection<CompilerServerJob>.TryTakeFromAnyCoreSlow()
	BlockingCollection<CompilerServerJob>.TryTakeFromAnyCore()
	BlockingCollection<CompilerServerJob>.TakeFromAny()
	CompilationQueue.Take()
	CompilerThread.CompilerThreadLoop()
	ThreadHelper.ThreadStart_Context()
	ExecutionContext.RunInternal()
	ExecutionContext.Run()
	ExecutionContext.Run()
	ThreadHelper.ThreadStart()

Burst-CompilerThread-2 @38052
	[Native Transition]
	WaitHandle.WaitMultiple()
	WaitHandle.WaitAny()
	WaitHandle.WaitAny()
	BlockingCollection<CompilerServerJob>.TryTakeFromAnyCoreSlow()
	BlockingCollection<CompilerServerJob>.TryTakeFromAnyCore()
	BlockingCollection<CompilerServerJob>.TakeFromAny()
	CompilationQueue.Take()
	CompilerThread.CompilerThreadLoop()
	ThreadHelper.ThreadStart_Context()
	ExecutionContext.RunInternal()
	ExecutionContext.Run()
	ExecutionContext.Run()
	ThreadHelper.ThreadStart()

Domain unloader @17904

Burst-CompilerThread-11 @20652
	[Native Transition]
	WaitHandle.WaitMultiple()
	WaitHandle.WaitAny()
	WaitHandle.WaitAny()
	BlockingCollection<CompilerServerJob>.TryTakeFromAnyCoreSlow()
	BlockingCollection<CompilerServerJob>.TryTakeFromAnyCore()
	BlockingCollection<CompilerServerJob>.TakeFromAny()
	CompilationQueue.Take()
	CompilerThread.CompilerThreadLoop()
	ThreadHelper.ThreadStart_Context()
	ExecutionContext.RunInternal()
	ExecutionContext.Run()
	ExecutionContext.Run()
	ThreadHelper.ThreadStart()

Burst-CompilerThread-3 @35924
	[Native Transition]
	WaitHandle.WaitMultiple()
	WaitHandle.WaitAny()
	WaitHandle.WaitAny()
	BlockingCollection<CompilerServerJob>.TryTakeFromAnyCoreSlow()
	BlockingCollection<CompilerServerJob>.TryTakeFromAnyCore()
	BlockingCollection<CompilerServerJob>.TakeFromAny()
	CompilationQueue.Take()
	CompilerThread.CompilerThreadLoop()
	ThreadHelper.ThreadStart_Context()
	ExecutionContext.RunInternal()
	ExecutionContext.Run()
	ExecutionContext.Run()
	ThreadHelper.ThreadStart()

Burst-CompilerThread-4 @1188
	[Native Transition]
	WaitHandle.WaitMultiple()
	WaitHandle.WaitAny()
	WaitHandle.WaitAny()
	BlockingCollection<CompilerServerJob>.TryTakeFromAnyCoreSlow()
	BlockingCollection<CompilerServerJob>.TryTakeFromAnyCore()
	BlockingCollection<CompilerServerJob>.TakeFromAny()
	CompilationQueue.Take()
	CompilerThread.CompilerThreadLoop()
	ThreadHelper.ThreadStart_Context()
	ExecutionContext.RunInternal()
	ExecutionContext.Run()
	ExecutionContext.Run()
	ThreadHelper.ThreadStart()

Burst-CompilerThread-5 @4956
	[Native Transition]
	WaitHandle.WaitMultiple()
	WaitHandle.WaitAny()
	WaitHandle.WaitAny()
	BlockingCollection<CompilerServerJob>.TryTakeFromAnyCoreSlow()
	BlockingCollection<CompilerServerJob>.TryTakeFromAnyCore()
	BlockingCollection<CompilerServerJob>.TakeFromAny()
	CompilationQueue.Take()
	CompilerThread.CompilerThreadLoop()
	ThreadHelper.ThreadStart_Context()
	ExecutionContext.RunInternal()
	ExecutionContext.Run()
	ExecutionContext.Run()
	ThreadHelper.ThreadStart()

Burst-CompilerThread-6 @18628
	[Native Transition]
	WaitHandle.WaitMultiple()
	WaitHandle.WaitAny()
	WaitHandle.WaitAny()
	BlockingCollection<CompilerServerJob>.TryTakeFromAnyCoreSlow()
	BlockingCollection<CompilerServerJob>.TryTakeFromAnyCore()
	BlockingCollection<CompilerServerJob>.TakeFromAny()
	CompilationQueue.Take()
	CompilerThread.CompilerThreadLoop()
	ThreadHelper.ThreadStart_Context()
	ExecutionContext.RunInternal()
	ExecutionContext.Run()
	ExecutionContext.Run()
	ThreadHelper.ThreadStart()

Burst-CompilerThread-7 @28696
	[Native Transition]
	WaitHandle.WaitMultiple()
	WaitHandle.WaitAny()
	WaitHandle.WaitAny()
	BlockingCollection<CompilerServerJob>.TryTakeFromAnyCoreSlow()
	BlockingCollection<CompilerServerJob>.TryTakeFromAnyCore()
	BlockingCollection<CompilerServerJob>.TakeFromAny()
	CompilationQueue.Take()
	CompilerThread.CompilerThreadLoop()
	ThreadHelper.ThreadStart_Context()
	ExecutionContext.RunInternal()
	ExecutionContext.Run()
	ExecutionContext.Run()
	ThreadHelper.ThreadStart()

Burst-CompilerThread-8 @4376
	[Native Transition]
	WaitHandle.WaitMultiple()
	WaitHandle.WaitAny()
	WaitHandle.WaitAny()
	BlockingCollection<CompilerServerJob>.TryTakeFromAnyCoreSlow()
	BlockingCollection<CompilerServerJob>.TryTakeFromAnyCore()
	BlockingCollection<CompilerServerJob>.TakeFromAny()
	CompilationQueue.Take()
	CompilerThread.CompilerThreadLoop()
	ThreadHelper.ThreadStart_Context()
	ExecutionContext.RunInternal()
	ExecutionContext.Run()
	ExecutionContext.Run()
	ThreadHelper.ThreadStart()

Burst-CompilerThread-9 @24856
	[Native Transition]
	WaitHandle.WaitMultiple()
	WaitHandle.WaitAny()
	WaitHandle.WaitAny()
	BlockingCollection<CompilerServerJob>.TryTakeFromAnyCoreSlow()
	BlockingCollection<CompilerServerJob>.TryTakeFromAnyCore()
	BlockingCollection<CompilerServerJob>.TakeFromAny()
	CompilationQueue.Take()
	CompilerThread.CompilerThreadLoop()
	ThreadHelper.ThreadStart_Context()
	ExecutionContext.RunInternal()
	ExecutionContext.Run()
	ExecutionContext.Run()
	ThreadHelper.ThreadStart()

Burst-ProgressReporter @28972
	[Native Transition]
	Monitor.ObjWait()
	Monitor.Wait()
	Monitor.Wait()
	SemaphoreSlim.WaitUntilCountOrTimeout()
	SemaphoreSlim.Wait()
	BlockingCollection<ProgressHelper.ReportProgressItem>.TryTakeWithNoTimeValidation()
	BlockingCollection<ProgressHelper.ReportProgressItem>.TryTake()
	BlockingCollection<ProgressHelper.ReportProgressItem>.Take()
	ProgressHelper.ReportProgressWorker()
	ThreadHelper.ThreadStart_Context()
	ExecutionContext.RunInternal()
	ExecutionContext.Run()
	ExecutionContext.Run()
	ThreadHelper.ThreadStart()```

**Comment by handzlikchris** [comment]
I think there's already a merged-in version for custom file watchers but it's using polling and likely slower than this (not great for bigger codebases). You can check it out in here for how to hook up yours with settings if you want
https://github.com/handzlikchris/FastScriptReload/pull/100

image

**Comment by handzlikchris** [comment]
No worries, I've not put that in - still waiting for you! ;) I think @D0rkKnight did.

It's still wanted, if good implementation - it'll can replace Unity's default one. I've seen more issues there, not sure if FileWatching isn't worse in newer versions.

**Comment by leohilbert** [comment]
> Oh no, I forgot about this! @handzlikchris I told you to yell viciously mean abuse at me, stop being so nice about it! :)
> 
> @leohilbert that hanging behaviour is definitely related to the watcher. I know about it and I know how to fix it - the easiest and most complete/reliable way is the full rewrite I mentioned above, which probably shouldn't take long actually. I'll give myself the goal of getting this completed by the end of the weekend. I'll make some reminders for myself, but please do hurl abuse at me if I forgot, that would be helpful.

@SamPruden I feel really bad about this, but since you specifically asked for it, I hereby hurl abuse at you. 💌

**Comment by handzlikchris** [comment]
Thanks @SamPruden I'll check it out.

I wouldn't worry about a chance that watcher will not fire, with the amount of changes people do - if it happens they'll probably just think they didn't save and make another change / save that should trigger workflow.

Tried to have a look just now but seems that latest commit 'small tidy up' shows a good bunch of changes (looks like a merge that's not recognised?).

Would you be able to reset to one commit before that and re-merge with master (or alternatively just leave without merging and I can do that).

For enabling this way of file-watching I'm leaning into refactoring `FastScriptReload.Editor.FastScriptReloadPreference.EnableCustomFileWatcher` option from bool to an `EnumProjectEditorPreferenceDefinition` that'll have
```
UnityApi
SimplePolling
WindowsApi
```

And then specifying `UnityApi` as default for new installs (via defaultValue on ctor) - once we've tested for a version or 2 and it holds up nicely we can promote that to default implementation for new-installs on windows.

Happy to get the integration done - just need to sort out that latest commit so it's clean for review.

Thanks again! Looks like great piece of work

**Comment by handzlikchris** [comment]
alright - I'll do some testing as well.

Yeah - 2019 is earliest supported

**Comment by handzlikchris** [comment]
This one's still on my radar. Sorry couldn't get to it earlier and now heading to Unite. I'll try to catch up next week

**Comment by leohilbert** [comment]
Hi, just wanted to chime in and say that Unity only got stuck once since I updated my project with the fix :)
I'm not even sure if this is related to this feature or it was just Unity doing Unity things. Thanks for building this, it works great for me! <3

**Review by handzlikchris — APPROVED** [review]

**Comment by handzlikchris** [comment]
Thanks guys, sorry for the delay - just going to add some UI options and will merge to main

**Comment by handzlikchris** [comment]
@SamPruden nice that works well and feels much quicker.

One thing that I found in testing, call to `ReadDirectoryChangesW` in `FastScriptReload.Editor.WindowsFileSystemWatcher.Monitor` actually freezes monitor thread if you've changed script that's in a symlink folder. Shouldn't be a big deal I'll make a note of that in UI if someone uses those

**Pull request merged**
